---
title : "PG2022 Clustering Demo"
author: "Frederick J Tan"
date  : "12 December 2022"
output: 
  html_notebook:
    toc: true
    toc_float: true
---

# Load packages

```{r}
# Load scran, scater for basic clustering
library( "scran" )
library( "scater" )
# Load bluster, pheatmap to explore clustering strategies
library( "bluster" )
library( "pheatmap" )
```

# Load data

```{r}
sce.pbmc <- readRDS( "/home/idies/workspace/practical_genomics/sce.pbmc.rds" )
```

```{r}
# Check that everything loaded
sce.pbmc
```

# Cluster

```{r}
# Save clusterCells() output in nn.clusters object
nn.clusters <- clusterCells( sce.pbmc, use.dimred="PCA" )
```

```{r}
# Store cluster labels as metadata
colLabels(sce.pbmc) <- nn.clusters
```

```{r}
# plotTSNE() with colour_by="label" and text_by
plotTSNE( sce.pbmc, colour_by="label", text_by="label" )
```

```{r}
# plotTSNE() of MS4A1 (B cells), CD14 (macrophages), CD8A (CD8+ T cells)
plotTSNE( sce.pbmc, colour_by="MS4A1" )
plotTSNE( sce.pbmc, colour_by="CD14" )
plotTSNE( sce.pbmc, colour_by="CD8A" )
```

# Explore clusterCells output

```{r}
# What class is the nn.clusters object?
class( nn.clusters )
```

```{r}
# What is the length of nn.clusters?
length( nn.clusters )
```

```{r}
# Create a table showing how many cells are in each cluster
table( nn.clusters )
```

```{r}
# Plot expression of marker genes
goi <- c( "MS4A1", "CD14", "CD8A" )
plotExpression( sce.pbmc, goi, x="label" )
```

# Adjust clustering strategy

```{r}
# Create nn.clusters2 object based on SNNGraphParam( k=50 )
nn.clusters2 <- clusterCells(
  sce.pbmc, use.dimred="PCA",
  BLUSPARAM=SNNGraphParam( k=50 )
)
```

```{r}
# How many cells are in each cluster?
table( nn.clusters2 )
```

```{r}
# Store cluster labels as metadata
colData(sce.pbmc)$label2 <- nn.clusters2
```

```{r}
# Check that metadata added
sce.pbmc
```

# Compare two clustering strategies

```{r}
# plotTSNE of label and label2
plotTSNE( sce.pbmc, colour_by="label" )
plotTSNE( sce.pbmc, colour_by="label2" )
```

```{r}
# Tabulate how cells from first clustering strategy overlap with second
tab <- table(
  paste( "A", nn.clusters ),
  paste( "B", nn.clusters2 )
)
```

```{r}
# Print out actual table
tab
```

```{r}
# Visualize by pheatmap
pheatmap( log10( tab+10 ) )
```

# Document software

- Quit the current R session
- Run All

```{r}
sessionInfo()
```

